### ISSUE TITLE
Be consistent in using array functions or anonymous functions

### ISSUE THREAD

**Issue by jmburges** [learn-co-students/jsOORenderLab#1]
https://github.com/learn-co-students/jsOORenderLab/blob/solution/lib/list.js

You use an anonymous function in filter, but an arrow function in map. Any reasons why?

**Comment by LKWLaLa** [comment]
Thank you!  I did that because when I double checked the filter syntax, the example used an anonymous function.  So I used that without thinking about consistency.  I've now changed it to an arrow function.

**Comment by jmburges** [comment]
Once you change it, go ahead and close this issue
