### ISSUE TITLE
onlyuse $ variables to hold jQuery elements

### ISSUE THREAD

**Issue by jmburges** [learn-co-students/jsOORenderLab#3]
https://github.com/learn-co-students/jsOORenderLab/blob/f151fc1e8000aca45802117c77e91a4d3bb92ad8/lib/index.js#L10-L11

Here you use `$name`. Normally we use $ variables to hold a jQuery element. Something like `let $name = ${"#name")` but you are storing the value in there. That's just a string so it shouldn't be prefixed with the `$`

**Comment by LKWLaLa** [comment]
Ok, thanks!!  fixed.  :)
