### ISSUE TITLE
Does your addListItem function work?

### ISSUE THREAD

**Issue by jmburges** [learn-co-students/jsOORenderLab#4]
here https://github.com/learn-co-students/jsOORenderLab/blob/f151fc1e8000aca45802117c77e91a4d3bb92ad8/lib/index.js#L10-L11

IT is attaching to `.name`. That seems like it would get a lot of different items. How do you make it so just gets the name of the item that was clicked?

**Comment by LKWLaLa** [comment]
`.name` is the class on the input element, which there is only one of.  The `addListItem` function simply creates a new Item object from whatever values you have typed into the input boxes, and then re-renders the List with the new Item included.   Is the overall concept confusing?

**Comment by jmburges** [comment]
Oh I understand. I wouldn't use classes for that. In general you'd use a class for something like `input-field` to style all input fields. If you have two different field, I would use id. It's effectively unique to that text field anyways
